services:
  chaser_website_back:
    image: chaser_website_back:latest
    container_name: "chaser_website"
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
      - ~/.ssh:/root/.ssh:ro
    ports:
      - "8090:8090"
    depends_on:
      - chaser_website_db
    restart: always
    networks:
      - "chaser_website_network"

  chaser_website_db:
    container_name: "chaser_website_db"
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5435:5435"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    env_file:
      - .env
    networks:
      - "chaser_website_network"

  chaser_website_pgadmin:
    container_name: "chaser_website_pgadmin"
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - chaser_website_db
    restart: always
    env_file:
      - .env
    networks:
      - "chaser_website_network"

volumes:
  postgres_data:

networks:
  chaser_website_network:
    driver: bridge