[project]
name = "chaser-website-API"
version = "0.1.0"
dependencies = [
  "fastapi>=0.112.0",
  "pydantic-settings>=2.4.0",
]
requires-python = ">=3.11"

description = "Chaser-Website-API"

[project.optional-dependencies]
dev = [
    "black",
    "flake8",
    "mypy",
    "pytest"
]